# Generated by Django 4.2.5 on 2023-09-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dingoapp', '0002_foodmodel_picture_alter_foodmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_level', models.CharField(max_length=50, verbose_name='Chef Level')),
            ],
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='picture',
            field=models.ImageField(upload_to='food/'),
        ),
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Title')),
                ('picture', models.ImageField(upload_to='chef/', verbose_name='Picture')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('X_twitter', models.URLField(blank=True, null=True, verbose_name='X')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('skype', models.URLField(blank=True, null=True, verbose_name='Skype')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dingoapp.cheflevel')),
            ],
        ),
    ]
