# Generated by Django 4.2.5 on 2023-09-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dingoapp', '0003_cheflevel_alter_foodmodel_picture_chefs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='chefs',
            options={'verbose_name': 'Chefs', 'verbose_name_plural': 'Chefses'},
        ),
    ]
