# Generated by Django 4.2.5 on 2023-09-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingoapp', '0005_bookingmodel_alter_chefs_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dingoapp.tagmodel', verbose_name='Tags'),
        ),
    ]
